#include "SFPLocalization.h"

#include "Internationalization/Culture.h"
#include "Internationalization/Internationalization.h"

namespace
{
	struct FTranslationPair
	{
		const TCHAR* German;
		const TCHAR* English;
	};

	// Complete UI labels are handled before the fragment catalog. The fragment
	// catalog also translates solver output and German text stored by older plans.
	constexpr FTranslationPair ExactTranslations[] = {
		{TEXT("Aus vorhandenen Eingängen planen"), TEXT("Plan from available inputs")},
		{TEXT("Freie Ausgaben wachsen gleichmäßig. Eine Mengenänderung setzt einen festen Wunsch. Eingänge begrenzen die Berechnung; weitere Rohstoffe werden ausgewiesen."), TEXT("Free outputs grow equally. Editing a rate sets a fixed request. Inputs limit production; additional resources are listed.")},
		{TEXT("Markiertes Produkt als Eingang hinzufügen"), TEXT("Add selected product as an input")},
		{TEXT("Produkt auswählen"), TEXT("Select product")},
		{TEXT("1. Endprodukte oder Eingänge festlegen.\n2. Plan berechnen, damit passende Maschinen erscheinen.\n3. Mk.-Stufe wählen.\n4. Erneut berechnen und den Plan speichern."), TEXT("1. Set final products or available inputs.\n2. Calculate a plan to see compatible machines.\n3. Choose the Mk. tier.\n4. Recalculate and save the plan.")},
        {TEXT("Maschinenauswahl geändert – bitte neu berechnen."), TEXT("Machine selection changed – please recalculate.")},
        {TEXT("Plan aktualisiert – zum Behalten speichern."), TEXT("Plan updated – save to keep it.")},
        {TEXT("Plan gespeichert."), TEXT("Plan saved.")},
        {TEXT("PRODUKTIONSMASCHINEN"), TEXT("PRODUCTION MACHINES")},
        {TEXT("MASCHINENEINSTELLUNGEN"), TEXT("MACHINE SETTINGS")},
        {TEXT("Maschinenvariante, Takt, Somersloops und Brennstoff werden pro Produktionsstufe eingestellt."), TEXT("Configure machine variant, clock, Somersloops and fuel per production step.")},
        {TEXT("Maschineneinstellung geändert – bitte neu berechnen."), TEXT("Machine setting changed – please recalculate.")},
        {TEXT("1. Endprodukte oder Eingänge festlegen.\n2. Plan berechnen, damit passende Maschinen erscheinen.\n3. Maschinenvariante, Takt, Somersloops und ggf. Brennstoff einstellen.\n4. Erneut berechnen und den Plan speichern."), TEXT("1. Set final products or inputs.\n2. Calculate the plan so matching machines appear.\n3. Configure machine variant, clock, Somersloops and fuel where applicable.\n4. Recalculate and save the plan.")},
        {TEXT("Nach der Berechnung erscheinen hier die verfügbaren Maschinenvarianten des Plans."), TEXT("Calculate a plan to see its available machine variants here.")},
        {TEXT("Maschinen geändert – Plan neu berechnen und speichern."), TEXT("Machines changed – recalculate and save the plan.")},
        {TEXT("Unterschiedliche Maschinen"), TEXT("Mixed machines")},
        {TEXT("Weitere Einstellungen"), TEXT("More settings")},
		{TEXT("Fest"), TEXT("Fixed")},
		{TEXT("Frei"), TEXT("Free")},
		{TEXT("Zusätzlich erforderlich"), TEXT("Additionally required")},
		{TEXT("Fehlbedarf"), TEXT("Shortfall")},
		{TEXT("Rest"), TEXT("Remaining")},
		{TEXT("Mindestens einen vorhandenen Eingang hinzufügen."), TEXT("Add at least one available input.")},
		{TEXT("Ungültige Eingangsmenge."), TEXT("Invalid input quantity.")},
		{TEXT("Ungültige Zielmenge."), TEXT("Invalid target quantity.")},
		{TEXT("Kein endliches Maximum innerhalb des Rechenbereichs. Weitere Eingänge begrenzen oder Ausgaben festlegen."), TEXT("No finite maximum within the calculation range. Limit additional inputs or fix output rates.")},
		{TEXT("Mit diesen Eingängen ist keine positive Ausgabe möglich. Eingänge oder Rezeptwahl anpassen."), TEXT("These inputs cannot produce a positive output. Adjust inputs or recipe selection.")},
		{TEXT("NICHT ERFÜLLBAR: Feste Wünsche überschreiten die Eingänge. Der Graph zeigt den Bedarf, nicht eine versorgte Fabrik."), TEXT("NOT FEASIBLE: Fixed requests exceed the inputs. The graph shows requirements, not a supplied factory.")},
		{TEXT("Berechnet für die gewählten Rezeptketten. Freie Ausgaben wurden gemeinsam maximiert."), TEXT("Calculated for the selected recipe chains. Free outputs were maximized together.")},
		{TEXT("Vorhandene Eingänge im Reiter Planung ändern und dort neu berechnen."), TEXT("Edit available inputs in the Planning tab and recalculate there.")},
		{TEXT("Zu viele Eingänge im Plan."), TEXT("Too many inputs in the plan.")},
		{TEXT("Ungültiger Eingang."), TEXT("Invalid input.")},
		{TEXT("Zu viele Ausgaben im Plan."), TEXT("Too many outputs in the plan.")},
		{TEXT("Ungültige Ausgabe."), TEXT("Invalid output.")},
		{TEXT("Eingangsplan unvollständig."), TEXT("Input plan is incomplete.")},

		{TEXT("REZEPTE & ROHSTOFFGEWINNUNG"), TEXT("RECIPES & RESOURCE EXTRACTION")},
		{TEXT("Direktabbau / Förderung"), TEXT("Mining / extraction")},
		{TEXT("Umwandlung"), TEXT("Conversion")},
		{TEXT("Alternative Rezepte"), TEXT("Alternate recipes")},
		{TEXT("Standardrezepte"), TEXT("Standard recipes")},
		{TEXT("Automatische Annahme – Quelle, Miner und Reinheit mit deiner Fabrik abgleichen."), TEXT("Automatic assumption – check source, miner and purity against your factory.")},
		{TEXT("Eigene Auswahl – nach Änderungen neu berechnen"), TEXT("Custom selection – recalculate after changes")},
		{TEXT("Ausgabe"), TEXT("Output")},
		{TEXT("Rohstoff & Miner"), TEXT("Raw resource & miner")},
		{TEXT("Rohstoff am Eingang"), TEXT("Raw resource input")},
		{TEXT("Verarbeitung im Miner: Das Zusatzmodul erzeugt die oben angegebene Ausgabe direkt aus dem Rohstoff. Für reinen Erzabbau mit separater Verarbeitung unter Bezugsweg ein Herstellungsrezept wählen und neu berechnen. Danach die Bohrköpfe beim benötigten Erz einstellen."), TEXT("Processing inside the miner: The module produces the output shown above directly from the raw resource. For raw ore extraction with separate processing, choose a manufacturing recipe under Supply method and recalculate. Then configure the drill heads for the required ore.")},
		{TEXT("Reiner Rohstoffabbau: Der Miner liefert den Rohstoff unverarbeitet. Die Auswahl unten gilt für diese Ausgabe."), TEXT("Raw resource extraction: The miner outputs the unprocessed resource. The settings below apply to this output.")},
		{TEXT("Bezugsweg"), TEXT("Supply method")},
		{TEXT("Quelle"), TEXT("Source")},
		{TEXT("Miner / Förderanlage"), TEXT("Miner / extractor")},
		{TEXT("Reinheit"), TEXT("Purity")},
		{TEXT("Module / Bohrkopf"), TEXT("Modules / drill head")},
		{TEXT("Betriebsflüssigkeit"), TEXT("Operating fluid")},
		{TEXT("Rezept"), TEXT("Recipe")},
		{TEXT("Bezugsweg geändert – jetzt Produktionsplan neu berechnen und speichern."), TEXT("Supply method changed – recalculate and save the plan.")},
		{TEXT("Diese Einstellungen bestätigen"), TEXT("Confirm these settings")},
		{TEXT("Auswahl bestätigt – Plan neu berechnen und speichern."), TEXT("Selection confirmed – recalculate and save the plan.")},
		{TEXT("Gesperrt – im aktuellen Spielstand nicht verfügbar. "), TEXT("Locked – unavailable in the current save. ")},
		{TEXT("Keine"), TEXT("None")},
		{TEXT("EINGÄNGE"), TEXT("INPUTS")},
		{TEXT("AUSGÄNGE"), TEXT("OUTPUTS")},
		{TEXT("↩ RÜCKFÜHRUNGEN · Nebenprodukte und Kreislaufmaterial zurück zu früheren Produktionsstufen"), TEXT("↩ RETURN FLOWS · Byproducts and cycle materials routed back to earlier production stages")},
		{TEXT("Gleiche Farbe = gleiches Material  ·  Gelb: Strom  ·  Goldener Rücklaufkorridor: Rückführung"), TEXT("Same colour = same material  ·  Yellow: power  ·  Gold return corridor: feedback flow")},
		{TEXT("Betriebsflüssigkeit nicht stabil bilanzierbar. Rezeptwahl oder Ziele anpassen."), TEXT("Operating fluid balance did not converge. Adjust recipes or targets.")},

		{TEXT("SCHLIESSEN  [ESC]"), TEXT("CLOSE  [ESC]")},
		{TEXT("HOTKEY"), TEXT("HOTKEY")},
		{TEXT("AUS"), TEXT("OFF")},
		{TEXT("DEAKTIVIERT"), TEXT("DISABLED")},
		{TEXT("TASTE DRÜCKEN …"), TEXT("PRESS A KEY …")},
		{TEXT("Klicken und anschließend die neue Tastenkombination drücken"), TEXT("Click, then press the new key combination")},
		{TEXT("Tastenkürzel deaktivieren; Terminal und Chatbefehl bleiben verfügbar"), TEXT("Disable the hotkey; terminal and chat command remain available")},
		{TEXT("Neue Tastenkombination drücken; Esc bricht ab, Rücktaste deaktiviert den Hotkey"), TEXT("Press a new key combination; Esc cancels, Backspace disables the hotkey")},
		{TEXT("Planner-Hotkey deaktiviert; Terminal und /sfpplanner open bleiben verfügbar"), TEXT("Planner hotkey disabled; terminal and /sfpplanner open remain available")},
		{TEXT("Hotkey-Änderung abgebrochen"), TEXT("Hotkey change cancelled")},
		{TEXT("z. B. Stahlwerk 120/min"), TEXT("e.g. Steelworks 120/min")},
		{TEXT("PERSÖNLICH"), TEXT("PERSONAL")},
		{TEXT("MULTIPLAYER"), TEXT("MULTIPLAYER")},
		{TEXT("Zwischen persönlichen Client-Plänen und gemeinsamen Multiplayer-Plänen wechseln"), TEXT("Switch between personal client plans and shared multiplayer plans")},
		{TEXT("SPEICHERN"), TEXT("SAVE")},
		{TEXT("Aktuellen Produktionsplan unter dem eingegebenen Namen speichern"), TEXT("Save the current production plan under the entered name")},
		{TEXT("LADEN"), TEXT("LOAD")},
		{TEXT("LÖSCHEN"), TEXT("DELETE")},
		{TEXT("1  PLANUNG"), TEXT("1  PLANNING")},
		{TEXT("Zielprodukt, Menge und alternative Rezepte"), TEXT("Final products, rates and alternate recipes")},
		{TEXT("2  STROMVERSORGUNG"), TEXT("2  POWER SUPPLY")},
		{TEXT("Nettoleistung, Generator, Brennstoff und Reserve"), TEXT("Net power, generator, fuel and reserve")},
		{TEXT("Nettoleistung, Erzeuger, Betriebsart und Reserve"), TEXT("Net power, generator, operating mode and reserve")},
		{TEXT("3  MASCHINEN"), TEXT("3  MACHINES")},
		{TEXT("Benötigte Maschinen, Anzahl und Leistung"), TEXT("Required machines, quantities and power")},
		{TEXT("4  RESSOURCEN & KOSTEN"), TEXT("4  RESOURCES & COSTS")},
		{TEXT("Rohstofflimits, Transport und Baumaterial"), TEXT("Resource limits, transport and construction materials")},
		{TEXT("5  PRODUKTIONSGRAPH"), TEXT("5  PRODUCTION GRAPH")},
		{TEXT("Vollflächiger zoombarer Produktionsgraph"), TEXT("Full-size zoomable production graph")},
		{TEXT("ENDPRODUKTE DER PRODUKTIONSSTÄTTE"), TEXT("FACTORY FINAL PRODUCTS")},
		{TEXT("Produkt oder Mod suchen ..."), TEXT("Search for a product or mod ...")},
		{TEXT("Nur freigeschaltete Rezepte und Transportstufen"), TEXT("Unlocked recipes and transport tiers only")},
		{TEXT("TRANSPORTSTUFEN"), TEXT("TRANSPORT TIERS")},
		{TEXT("FÖRDERBAND"), TEXT("CONVEYOR BELT")},
		{TEXT("FÖRDERLIFT"), TEXT("CONVEYOR LIFT")},
		{TEXT("Menge des markierten Produkts pro Minute"), TEXT("Rate per minute for the selected product")},
		{TEXT("+ ZIEL HINZUFÜGEN"), TEXT("+ ADD TARGET")},
		{TEXT("Markiertes Produkt mit dieser Rate zur gemeinsamen Produktionsstätte hinzufügen"), TEXT("Add the selected product at this rate to the shared factory")},
		{TEXT("GEWÄHLTE ENDPRODUKTE"), TEXT("SELECTED FINAL PRODUCTS")},
		{TEXT("Mittlere Verbindungslänge für die Kostenschätzung (m)"), TEXT("Average connection length for cost estimates (m)")},
		{TEXT("MEHRPRODUKT-PLAN BERECHNEN"), TEXT("CALCULATE MULTI-PRODUCT PLAN")},
		{TEXT("ALTERNATIVE REZEPTE"), TEXT("ALTERNATE RECIPES")},
		{TEXT("AUTOMATIK"), TEXT("AUTOMATIC")},
		{TEXT("PLANSTATUS"), TEXT("PLAN STATUS")},
		{TEXT("STROMVERSORGUNG PLANEN"), TEXT("PLAN POWER SUPPLY")},
		{TEXT("Generatoren und Brennstoffe kommen direkt aus dem aktiven Spielstand. Die komplette Brennstoffkette wird in den Produktionsgraphen aufgenommen."), TEXT("Generators and fuels are read directly from the active save. The complete fuel chain is included in the production graph.")},
		{TEXT("Generatoren, modulare Komponenten und Brennstoffe kommen direkt aus dem aktiven Spielstand. Die vollständige Erzeugungskette wird in den Produktionsgraphen aufgenommen."), TEXT("Generators, modular components and fuels are read directly from the active save. The complete generation chain is included in the production graph.")},
		{TEXT("GEWÜNSCHTE NETTOLEISTUNG (MW)"), TEXT("DESIRED NET POWER (MW)")},
		{TEXT("SICHERHEITSRESERVE (%)"), TEXT("SAFETY RESERVE (%)")},
		{TEXT("Nur freigeschaltete Generatoren, Brennstoffe und Rezepte"), TEXT("Unlocked generators, fuels and recipes only")},
		{TEXT("Nur freigeschaltete Generatoren, Komponenten, Brennstoffe und Rezepte"), TEXT("Unlocked generators, components, fuels and recipes only")},
		{TEXT("GENERATOR"), TEXT("GENERATOR")},
		{TEXT("BRENNSTOFF"), TEXT("FUEL")},
		{TEXT("BRENNSTOFF / BETRIEBSART"), TEXT("FUEL / OPERATING MODE")},
		{TEXT("MITTLERE VERBINDUNGSLÄNGE (M)"), TEXT("AVERAGE CONNECTION LENGTH (M)")},
		{TEXT("NETTO-STROMPLAN BERECHNEN"), TEXT("CALCULATE NET POWER PLAN")},
		{TEXT("NETZBILANZ & BRENNSTOFFKETTE"), TEXT("GRID BALANCE & FUEL CHAIN")},
		{TEXT("NETZBILANZ & ERZEUGUNGSKETTE"), TEXT("GRID BALANCE & GENERATION CHAIN")},
		{TEXT("MASCHINENÜBERSICHT"), TEXT("MACHINE OVERVIEW")},
		{TEXT("Maschinenvariante"), TEXT("Machine variant")},
		{TEXT("Unterschiedliche Maschinen"), TEXT("Different machines")},
		{TEXT("GENERATOR-TAKT (%)"), TEXT("GENERATOR CLOCK (%)")},
		{TEXT("Stromgeneratoren können übertaktet, aber nicht mit Somersloops verstärkt werden."), TEXT("Power generators can be overclocked, but cannot be boosted with Somersloops.")},
		{TEXT("Generator-Takt geändert – Stromplan neu berechnen"), TEXT("Generator clock changed – recalculate the power plan")},
		{TEXT("Der Generator-Takt muss zwischen 1 und 100000 Prozent liegen"), TEXT("Generator clock must be between 1 and 100000 percent")},
		{TEXT("Max. Takt (%)"), TEXT("Max clock (%)")},
		{TEXT("Takt (%)"), TEXT("Clock (%)")},
		{TEXT("Sloops / Maschine"), TEXT("Sloops / machine")},
		{TEXT("Boost:"), TEXT("Boost:")},
		{TEXT("Power-Exponent:"), TEXT("Power exponent:")},
		{TEXT("Der Solver füllt Maschinen bis zu diesem Takt und untertaktet nur die letzte Maschine passend zum Bedarf."), TEXT("The solver fills machines up to this clock and underclocks only the final machine to match demand.")},
		{TEXT("Somersloops je Maschine"), TEXT("Somersloops per machine")},
		{TEXT("Brennstoff"), TEXT("Fuel")},
		{TEXT("Automatisch"), TEXT("Automatic")},
		{TEXT("Nach der Berechnung erscheinen hier Maschinenvarianten, Taktung und Produktionsverstärkung des Plans."), TEXT("After calculation, machine variants, clocking and production amplification for the plan appear here.")},
		{TEXT("Taktung geändert – bitte Produktionsplan neu berechnen."), TEXT("Clocking changed – recalculate the production plan.")},
		{TEXT("Somersloop-Einstellung geändert – bitte Produktionsplan neu berechnen."), TEXT("Somersloop setting changed – recalculate the production plan.")},
		{TEXT("Brennstoff geändert – bitte Produktionsplan neu berechnen."), TEXT("Fuel changed – recalculate the production plan.")},
		{TEXT("VERFÜGBARE ROHSTOFFE PRO MINUTE"), TEXT("AVAILABLE RESOURCES PER MINUTE")},
		{TEXT("Werte anpassen; der knappste Eingang skaliert alle Endproduktraten proportional."), TEXT("Adjust the values; the most constrained input scales all final-product rates proportionally.")},
		{TEXT("Aus allen eingetragenen Rohstofflimits neu berechnen"), TEXT("Recalculate from all entered resource limits")},
		{TEXT("AUS ROHSTOFFLIMITS BERECHNEN"), TEXT("CALCULATE FROM RESOURCE LIMITS")},
		{TEXT("BEDARF, TRANSPORT UND BAUKOSTEN"), TEXT("DEMAND, TRANSPORT & CONSTRUCTION COSTS")},
		{TEXT("PRODUKTIONSGRAPH"), TEXT("PRODUCTION GRAPH")},
		{TEXT("Kästchen im Knoten: erledigt/offen   •   Mausrad: Zoom   •   Ziehen: Verschieben"), TEXT("Node checkbox: complete/open   •   Mouse wheel: zoom   •   Drag: pan")},
		{TEXT("GRAPH ZENTRIEREN"), TEXT("CENTER GRAPH")},
		{TEXT("ENTFERNEN"), TEXT("REMOVE")},
		{TEXT("Rezept wählen"), TEXT("Choose recipe")},
		{TEXT("Kein Förderband geladen"), TEXT("No conveyor belt loaded")},
		{TEXT("Kein Förderlift geladen"), TEXT("No conveyor lift loaded")},
		{TEXT("Kein Generator geladen"), TEXT("No generator loaded")},
		{TEXT("Kein Brennstoff geladen"), TEXT("No fuel loaded")},
		{TEXT("Keine Transportstufe geladen"), TEXT("No transport tier loaded")},
		{TEXT("Noch keine benannten Pläne"), TEXT("No named plans yet")},
		{TEXT("Gespeicherten Plan auswählen ..."), TEXT("Select a saved plan ...")},
		{TEXT("Noch keine Multiplayer-Pläne"), TEXT("No multiplayer plans yet")},
		{TEXT("Multiplayer-Plan auswählen ..."), TEXT("Select a multiplayer plan ...")},
		{TEXT("Multiplayer-Pläne: gemeinsam gespeichert und für alle Spieler synchronisiert"), TEXT("Multiplayer plans: shared storage and synchronization for all players")},
		{TEXT("Persönliche Pläne: nur auf diesem Client gespeichert"), TEXT("Personal plans: stored only on this client")},
		{TEXT("Bestehenden Multiplayer-Plan vor dem Überschreiben zuerst laden"), TEXT("Load the existing multiplayer plan before overwriting it")},
		{TEXT("Eine Multiplayer-Plan-Anfrage läuft bereits"), TEXT("A multiplayer-plan request is already in progress")},
		{TEXT("Multiplayer-Plan-Synchronisierung läuft; neuer Fortschritt wird danach übertragen"), TEXT("Multiplayer-plan synchronization is in progress; new progress will be sent afterwards")},
		{TEXT("Baufortschritt wird mit dem Multiplayer-Plan synchronisiert …"), TEXT("Synchronizing build progress with the multiplayer plan …")},
		{TEXT("Empfangener Multiplayer-Plan enthält keine gültigen Servermetadaten"), TEXT("Received multiplayer plan has no valid server metadata")},
		{TEXT("Ungültiges Produkt"), TEXT("Invalid product")},
		{TEXT("Ungültiges Ziel"), TEXT("Invalid target")},
		{TEXT("Ungültiges Rezept"), TEXT("Invalid recipe")},
		{TEXT("Ungültiger Eingang"), TEXT("Invalid input")},
		{TEXT("Ungültiger gespeicherter Plan"), TEXT("Invalid saved plan")},
		{TEXT("Kein gültiger Spielstand geladen"), TEXT("No valid game session is loaded")},
		{TEXT("Der Rezeptmanager ist noch nicht bereit"), TEXT("The recipe manager is not ready yet")},
		{TEXT("Keine maschinenproduzierten Gegenstände gefunden"), TEXT("No machine-produced items found")},
		{TEXT("Für mindestens einen angezeigten Splitter, Fusionator oder eine Pipeline Junction wurde kein Baukosten-Rezept gefunden"), TEXT("No construction recipe was found for at least one displayed splitter, merger or pipeline junction")},
		{TEXT("Die gewünschte Nettoleistung muss größer als 0 MW sein"), TEXT("The desired net power must be greater than 0 MW")},
		{TEXT("Die Leistungsreserve muss zwischen 0 und 500 Prozent liegen"), TEXT("The power reserve must be between 0 and 500 percent")},
		{TEXT("Keine brennstoffbetriebenen Generatoren im aktiven Rezeptkatalog gefunden"), TEXT("No fuel-powered generators were found in the active recipe catalog")},
		{TEXT("Keine vollständigen Stromerzeuger im aktiven Baukatalog gefunden"), TEXT("No complete power generators were found in the active build catalog")},
		{TEXT("Die gewählte Generator-/Brennstoffkombination ist in diesem Spielstand nicht freigeschaltet"), TEXT("The selected generator/fuel combination is not unlocked in this save")},
		{TEXT("Die gewählte Generator-/Brennstoffkombination ist nicht geladen"), TEXT("The selected generator/fuel combination is not loaded")},
		{TEXT("Für diese Stromvorgabe konnte keine stabile Brennstoffkette berechnet werden"), TEXT("No stable fuel chain could be calculated for this power target")},
		{TEXT("Für diese Stromvorgabe konnte keine vollständige Erzeugungskette berechnet werden"), TEXT("No complete generation chain could be calculated for this power target")},
		{TEXT("Mindestens ein gespeichertes Endprodukt ist im aktuellen Rezeptkatalog nicht mehr vorhanden"), TEXT("At least one saved final product is no longer present in the current recipe catalog")},
		{TEXT("Es ist kein berechneter Produktionsplan vorhanden"), TEXT("No calculated production plan is available")},
		{TEXT("Der Produktionsplan konnte nicht als JSON serialisiert werden"), TEXT("The production plan could not be serialized as JSON")},
		{TEXT("Gespeicherter Produktionsplan enthält ungültiges JSON"), TEXT("Saved production plan contains invalid JSON")},
		{TEXT("Gespeicherter Produktionsplan hat eine nicht unterstützte Version"), TEXT("Saved production plan has an unsupported version")},
		{TEXT("Gespeicherter Produktionsplan enthält keine Knoten"), TEXT("Saved production plan contains no nodes")},
		{TEXT("Gespeicherter Produktionsplan enthält keine Verbindungen"), TEXT("Saved production plan contains no connections")},
		{TEXT("Gespeicherter Produktionsplan ist leer oder beschädigt"), TEXT("Saved production plan is empty or corrupted")},
		{TEXT("Bitte einen Namen für den Produktionsplan eingeben"), TEXT("Enter a name for the production plan")},
		{TEXT("Ungültiger Dateiname für den gespeicherten Plan"), TEXT("Invalid file name for the saved plan")},
		{TEXT("ALIEN POWER AUGMENTER"), TEXT("ALIEN POWER AUGMENTER")},
		{TEXT("Augmenter werden als Teil desselben Stromnetzes berechnet. Mit Matrix versorgte Augmenter planen zusätzlich den Matrix-Bedarf und dessen Produktionskette."), TEXT("Augmenters are calculated as part of the same power grid. Matrix-fed augmenters also plan the Matrix demand and its production chain.")},
		{TEXT("Passiv (+Basisleistung / Netzboost)"), TEXT("Passive (+base power / grid boost)")},
		{TEXT("Mit Alien Power Matrix versorgt"), TEXT("Fed with Alien Power Matrix")},
		{TEXT("Alien Power Augmenter geändert – Stromplan neu berechnen"), TEXT("Alien Power Augmenter changed – recalculate the power plan")},
		{TEXT("Alien Power Augmenter mit Matrix geändert – Stromplan neu berechnen"), TEXT("Matrix-fed Alien Power Augmenter changed – recalculate the power plan")},
		{TEXT("Die Anzahl der Alien Power Augmenter ist ungültig"), TEXT("The Alien Power Augmenter count is invalid")},
		{TEXT("Alien Power Augmenter konnte im aktiven Spielstand nicht gefunden werden"), TEXT("Alien Power Augmenter could not be found in the active save")},
		{TEXT("Alien Power Augmenter ist in diesem Spielstand noch nicht freigeschaltet"), TEXT("Alien Power Augmenter is not unlocked in this save")},
		{TEXT("Alien Power Matrix konnte für den gespeisten Power Augmenter nicht gefunden werden"), TEXT("Alien Power Matrix could not be found for the fueled Power Augmenter")},
		{TEXT("Der Multiplayer-Plan enthält eine ungültige Anzahl Alien Power Augmenter"), TEXT("The multiplayer plan contains an invalid Alien Power Augmenter count")},
		{TEXT("Stromnetz"), TEXT("Power grid")},
		{TEXT("Elektrische Leistung"), TEXT("Electric power")},
		{TEXT("Kein Brennstoff"), TEXT("No fuel")},
		{TEXT("Rotationsenergie"), TEXT("Rotational energy")},
		{TEXT("Prozesswärme"), TEXT("Process heat")},
		{TEXT("PRODUKTIONSPLAN"), TEXT("PRODUCTION PLAN")},
		{TEXT("ROHSTOFFE / EXTERN"), TEXT("RESOURCES / EXTERNAL")},
		{TEXT("ROHSTOFFE / START"), TEXT("RESOURCES / START")},
		{TEXT("DIREKTE ZUFUHR"), TEXT("DIRECT INPUT")},
		{TEXT("VERTEILUNG"), TEXT("ROUTING")},
		{TEXT("NETTO-STROMZIEL"), TEXT("NET POWER TARGET")},
		{TEXT("ENDPRODUKTE"), TEXT("FINAL PRODUCTS")},
		{TEXT("ENDPRODUKTE / NEBENSTRÖME"), TEXT("FINAL PRODUCTS / BYPRODUCTS")},
		{TEXT("LAGER / NEBENSTRÖME"), TEXT("STORAGE / BYPRODUCTS")},
		{TEXT("Produkt wählen und auf 'Berechnen' klicken"), TEXT("Select a product and click 'Calculate'")},
		{TEXT("Mausrad: Zoom  ·  Mittlere/rechte Maustaste: verschieben  ·  Doppelklick: einpassen"), TEXT("Mouse wheel: zoom  ·  Middle/right mouse: pan  ·  Double-click: fit")},
		{TEXT("Mausrad: Zoom  ·  Mittlere/rechte Maustaste: verschieben  ·  Doppelklick: lesbar ausrichten"), TEXT("Mouse wheel: zoom  ·  Middle/right mouse: pan  ·  Double-click: align readable")},
		{TEXT("Gleiche Farbe = gleiches Material  ·  Gelb: Strom  ·  Blau: Flüssigkeit  ·  Violett: Gas  ·  Türkis: lokaler Miner"), TEXT("Same color = same material  ·  Yellow: power  ·  Blue: liquid  ·  Purple: gas  ·  Teal: local miner")}
	};

	constexpr FTranslationPair FragmentTranslations[] = {
		// Some content mods persist or expose German display names even while the
		// active game language is English. These graph-facing fallbacks keep old
		// saved plans and those runtime descriptors readable without renaming the
		// underlying recipes or item classes.
		{TEXT("Zerkleinertes Zink"), TEXT("Crushed Zinc")},
		{TEXT("Zerkleinertes Eisen"), TEXT("Crushed Iron")},
		{TEXT("Zerkleinertes Kupfer"), TEXT("Crushed Copper")},
		{TEXT("Zerkleinertes Nickel"), TEXT("Crushed Nickel")},
		{TEXT("Zerkleinertes Blei"), TEXT("Crushed Lead")},
		{TEXT("Eisenschmelze"), TEXT("Molten Iron")},
		{TEXT("Kupferschmelze"), TEXT("Molten Copper")},
		{TEXT("Zinkschmelze"), TEXT("Molten Zinc")},
		{TEXT("Nickelschmelze"), TEXT("Molten Nickel")},
		{TEXT("Bleischmelze"), TEXT("Molten Lead")},
		{TEXT("Kohlepulver"), TEXT("Coal Powder")},
		{TEXT("Pipeline-Kreuzung"), TEXT("Pipeline Junction")},
		{TEXT("Schmelzofen"), TEXT("Smelter")},
		{TEXT("Gangart"), TEXT("Gangue")},
		{TEXT("Dampf"), TEXT("Steam")},
        {TEXT("Rezeptleistung bei 100% je Maschine:"), TEXT("Recipe power per machine at 100%:")},
        {TEXT("Zyklusmittel ca."), TEXT("Approx. cycle average")},
        {TEXT("Variable Rezeptleistung: Die Leistungssumme verwendet numerische Zyklusmittelwerte. Spitzen können höher liegen; Netzreserve einplanen."), TEXT("Variable recipe power: totals use numerical cycle averages. Peaks can be higher; allow grid reserve.")},
        {TEXT("Produktionsmaschine"), TEXT("Production machine")},
        {TEXT("Produktionsfaktor:"), TEXT("Production multiplier:")},
        {TEXT("Produktionsverstärkung:"), TEXT("Production amplification:")},
        {TEXT("Leistungsexponent:"), TEXT("power exponent:")},
        {TEXT("Somersloops:"), TEXT("Somersloops:")},
        {TEXT("Brennleistung"), TEXT("Burner power")},
        {TEXT("Leistung bei 100%:"), TEXT("Power at 100%:")},
		{TEXT("ENDPRODUKTE"), TEXT("FINAL PRODUCTS")},
		{TEXT("Freie Ausgaben wachsen gleichmäßig. Eine Mengenänderung setzt einen festen Wunsch. Eingänge begrenzen die Berechnung; weitere Rohstoffe werden ausgewiesen."), TEXT("Free outputs grow equally. Editing a rate sets a fixed request. Inputs limit production; additional resources are listed.")},
		{TEXT("Markiertes Produkt als Eingang hinzufügen"), TEXT("Add selected product as an input")},
		{TEXT("Mindestens einen vorhandenen Eingang hinzufügen."), TEXT("Add at least one available input.")},
		{TEXT("Kein endliches Maximum innerhalb des Rechenbereichs. Weitere Eingänge begrenzen oder Ausgaben festlegen."), TEXT("No finite maximum within the calculation range. Limit additional inputs or fix output rates.")},
		{TEXT("Mit diesen Eingängen ist keine positive Ausgabe möglich. Eingänge oder Rezeptwahl anpassen."), TEXT("These inputs cannot produce a positive output. Adjust inputs or recipe selection.")},
		{TEXT("NICHT ERFÜLLBAR: Feste Wünsche überschreiten die Eingänge. Der Graph zeigt den Bedarf, nicht eine versorgte Fabrik."), TEXT("NOT FEASIBLE: Fixed requests exceed the inputs. The graph shows requirements, not a supplied factory.")},
		{TEXT("Berechnet für die gewählten Rezeptketten. Freie Ausgaben wurden gemeinsam maximiert."), TEXT("Calculated for the selected recipe chains. Free outputs were maximized together.")},
		{TEXT("Vorhandene Eingänge im Reiter Planung ändern und dort neu berechnen."), TEXT("Edit available inputs in the Planning tab and recalculate there.")},

		// Longer phrases must precede their component words.
		{TEXT("Planner-Hotkey gespeichert:"), TEXT("Planner hotkey saved:")},
		{TEXT("Hotkey konnte nicht gespeichert werden:"), TEXT("Hotkey could not be saved:")},
		{TEXT("Die gewählte Taste ist ungültig"), TEXT("The selected key is invalid")},
		{TEXT("Umschalt-, Strg-, Alt- oder Cmd-Taste benötigen eine zusätzliche Taste"), TEXT("Shift, Ctrl, Alt or Cmd requires an additional key")},
		{TEXT("Bitte genau eine Haupttaste angeben"), TEXT("Specify exactly one primary key")},
		{TEXT("Keine Taste angegeben"), TEXT("No key specified")},
		{TEXT("Unbekannte Taste"), TEXT("Unknown key")},
		{TEXT("Noch kein Stromplan berechnet."), TEXT("No power plan has been calculated yet.")},
		{TEXT("Noch kein Produktionsplan berechnet."), TEXT("No production plan has been calculated yet.")},
		{TEXT("Im Tab PLANUNG Endprodukte und ihre gewünschten Mengen hinzufügen."), TEXT("Add final products and their desired rates on the PLANNING tab.")},
		{TEXT("Nach der Berechnung erscheinen hier Rohstoffbedarf, Transportmengen und sämtliche Baukosten."), TEXT("After calculation, resource demand, transport volumes and all construction costs appear here.")},
		{TEXT("Nettoziel und Sicherheitsreserve festlegen. Generator und Brennstoff können gezielt gewählt oder der Automatik überlassen werden."), TEXT("Set the net target and safety reserve. Select a generator and fuel, or let Automatic choose them.")},
		{TEXT("Nettoziel und Sicherheitsreserve festlegen. Generator und Betriebsart können gezielt gewählt oder der Automatik überlassen werden."), TEXT("Set the net target and safety reserve. Select a generator and operating mode, or let Automatic choose them.")},
		{TEXT("Vollständige Maschinen-, Transport-, Baukosten- und Rezeptdetails stehen in den übrigen Tabs."), TEXT("Complete machine, transport, construction-cost and recipe details are available on the other tabs.")},
		{TEXT("Produktionsleistung bereits im Eigenverbrauch abgezogen"), TEXT("production power already deducted as self-consumption")},
		{TEXT("Komponenten- und Produktionsleistung bereits im Eigenverbrauch abgezogen"), TEXT("component and production power already deducted as self-consumption")},
		{TEXT("Maschinen und Generatoren tatsächlich bauen"), TEXT("machines and generators to build")},
		{TEXT("Maschinen tatsächlich bauen"), TEXT("machines to build")},
		{TEXT("Anlagenkomponente"), TEXT("plant component")},
		{TEXT("Maschinen und Generatoren nach Zweig"), TEXT("MACHINES AND GENERATORS BY BRANCH")},
		{TEXT("MASCHINEN UND GENERATOREN NACH ZWEIG"), TEXT("MACHINES AND GENERATORS BY BRANCH")},
		{TEXT("ROUTING NACH INGAME-NAME"), TEXT("ROUTING BY IN-GAME NAME")},
		{TEXT("BENÖTIGTE EXTERNE EINGÄNGE"), TEXT("REQUIRED EXTERNAL INPUTS")},
		{TEXT("GESCHÄTZTES MATERIAL FÜR BÄNDER, ROHRE UND VERTEILUNG"), TEXT("ESTIMATED MATERIAL FOR BELTS, PIPES AND ROUTING")},
		{TEXT("BAUMATERIAL FÜR MASCHINEN"), TEXT("CONSTRUCTION MATERIALS FOR MACHINES")},
		{TEXT("GESAMTES BAUMATERIAL"), TEXT("TOTAL CONSTRUCTION MATERIALS")},
		{TEXT("Transportmaterial ist eine Schätzung. Förderlifte begrenzen die Linienkapazität; ihre Anzahl und Höhe können aus dem logischen Graphen nicht zuverlässig abgeleitet werden. Steigungen und Umwege werden nicht automatisch vermessen."), TEXT("Transport material is an estimate. Conveyor lifts limit line capacity; their quantity and height cannot be derived reliably from the logical graph. Slopes and detours are not measured automatically.")},
		{TEXT("Keine externen Eingänge ermittelt"), TEXT("No external inputs found")},
		{TEXT("Keine Nebenprodukte ermittelt"), TEXT("No byproducts found")},
		{TEXT("Keine Kosten ermittelt"), TEXT("No costs found")},
		{TEXT("NEBENPRODUKTE & ABFALL"), TEXT("BYPRODUCTS & WASTE")},
		{TEXT("EXTERNE ROHSTOFFE"), TEXT("EXTERNAL RESOURCES")},
		{TEXT("BRENNSTOFFKETTE"), TEXT("FUEL CHAIN")},
		{TEXT("ERZEUGUNGSKETTE"), TEXT("GENERATION CHAIN")},
		{TEXT("TRANSPORTSCHÄTZUNG"), TEXT("TRANSPORT ESTIMATE")},
		{TEXT("Generatorbasis vor Augmenter"), TEXT("Generator base before augmenters")},
		{TEXT("Augmenter-Basisleistung"), TEXT("Augmenter base power")},
		{TEXT("Augmenter-Beitrag zur Bruttoerzeugung"), TEXT("Augmenter contribution to gross generation")},
		{TEXT("Alien-verstärkte Leistung"), TEXT("Alien-augmented power")},
		{TEXT("Netzfaktor"), TEXT("Grid multiplier")},
		{TEXT("Mit Matrix"), TEXT("With Matrix")},
		{TEXT("Passiv"), TEXT("Passive")},
		{TEXT("NETZBILANZ"), TEXT("GRID BALANCE")},
		{TEXT("ERZEUGUNG"), TEXT("GENERATION")},
		{TEXT("Zielverbrauch"), TEXT("Target demand")},
		{TEXT("Bruttoerzeugung"), TEXT("Gross generation")},
		{TEXT("Eigenverbrauch der Brennstoffkette"), TEXT("Fuel-chain self-consumption")},
		{TEXT("Eigenverbrauch der Erzeugungskette"), TEXT("Generation-chain self-consumption")},
		{TEXT("Reale Nettoleistung"), TEXT("Actual net power")},
		{TEXT("Verbleibende Reserve"), TEXT("Remaining reserve")},
		{TEXT("Generatorleistung"), TEXT("Generator power")},
		{TEXT("Generatoren bauen"), TEXT("generators to build")},
		{TEXT("Brennstoffbedarf"), TEXT("Fuel demand")},
		{TEXT("Kein Brennstoffbedarf"), TEXT("No fuel required")},
		{TEXT("Betriebsart"), TEXT("Operating mode")},
		{TEXT("AUTOMATISCH ANORDNEN"), TEXT("AUTO LAYOUT")},
		{TEXT("Baufortschritt:"), TEXT("Build progress:")},
		{TEXT("BAUFORTSCHRITT"), TEXT("BUILD PROGRESS")},
		{TEXT("Knoten erledigt"), TEXT("nodes completed")},
		{TEXT("wieder geöffnet"), TEXT("reopened")},
		{TEXT("automatisches Speichern fehlgeschlagen"), TEXT("automatic save failed")},
		{TEXT("Routing-Bauwerke"), TEXT("routing buildings")},
		{TEXT("MW Eigenverbrauch"), TEXT("MW self-consumption")},
		{TEXT("Strombedarf bei geplanter Taktung"), TEXT("Power demand at planned clock speeds")},
        {TEXT("Zyklusmittelwert bei variablem Verbrauch"), TEXT("Cycle average for variable power consumption")},
        {TEXT("MW Basisleistung"), TEXT("MW base power")},
		{TEXT("MW Basis"), TEXT("MW base power")},
		{TEXT("MW brutto"), TEXT("MW gross")},
		{TEXT("MW netto"), TEXT("MW net")},
		{TEXT("MW Reserve"), TEXT("MW reserve")},
		{TEXT("Netto-Stromplan"), TEXT("Net power plan")},
		{TEXT("Berechnung:"), TEXT("Calculation:")},
		{TEXT("Hinweise"), TEXT("Notes")},
		{TEXT("weitere"), TEXT("more")},
		{TEXT("Initialisierung fehlgeschlagen"), TEXT("Initialization failed")},
		{TEXT("Planner konnte nicht geöffnet werden"), TEXT("Planner could not be opened")},
		{TEXT("Unbekannte Aktion"), TEXT("Unknown action")},
		{TEXT("Nutze /sfpplanner"), TEXT("Use /sfpplanner")},
		{TEXT("Export abgeschlossen:"), TEXT("Export complete:")},
		{TEXT("Freischaltungsfilter geändert – Plan neu berechnen"), TEXT("Unlock filter changed – recalculate the plan")},
		{TEXT("Förderband geändert – Produktionsplan neu berechnen"), TEXT("Conveyor belt changed – recalculate the production plan")},
		{TEXT("Förderlift geändert – Produktionsplan neu berechnen"), TEXT("Conveyor lift changed – recalculate the production plan")},
		{TEXT("Generator geändert – Stromplan neu berechnen"), TEXT("Generator changed – recalculate the power plan")},
		{TEXT("Brennstoff geändert – Stromplan neu berechnen"), TEXT("Fuel changed – recalculate the power plan")},
		{TEXT("Nettoleistungsziel geändert – Stromplan neu berechnen"), TEXT("Net power target changed – recalculate the power plan")},
		{TEXT("Leistungsreserve geändert – Stromplan neu berechnen"), TEXT("Power reserve changed – recalculate the power plan")},
		{TEXT("mindestens eines freigeschaltet"), TEXT("at least one unlocked")},
		{TEXT("derzeit gesperrt"), TEXT("currently locked")},
		{TEXT("mögliche Rezepte"), TEXT("possible recipes")},
		{TEXT("Menge festlegen und Ziel hinzufügen"), TEXT("set the rate and add the target")},
		{TEXT("Markiert:"), TEXT("Selected:")},
		{TEXT("Bitte zuerst ein Produkt markieren"), TEXT("Select a product first")},
		{TEXT("Die Endproduktmenge muss größer als 0 sein"), TEXT("The final-product rate must be greater than 0")},
		{TEXT("aktualisiert"), TEXT("updated")},
		{TEXT("hinzugefügt"), TEXT("added")},
		{TEXT("ausgewählt"), TEXT("selected")},
		{TEXT("entfernt — Plan neu berechnen, um die Änderung zu übernehmen"), TEXT("removed — recalculate the plan to apply the change")},
		{TEXT("Zielmenge geändert — Plan neu berechnen"), TEXT("Target rate changed — recalculate the plan")},
		{TEXT("Plan neu berechnen"), TEXT("Recalculate plan")},
		{TEXT("Der Planner-Solver ist nicht verfügbar"), TEXT("The planner solver is unavailable")},
		{TEXT("Bitte mindestens ein Endprodukt hinzufügen"), TEXT("Add at least one final product")},
		{TEXT("Generator- und Brennstoffauswahl konnten nicht geladen werden"), TEXT("Generator and fuel choices could not be loaded")},
		{TEXT("Förderband und Förderlift müssen für die Brennstoffkette ausgewählt sein"), TEXT("A conveyor belt and conveyor lift must be selected for the fuel chain")},
		{TEXT("Förderband und Förderlift müssen für die Produktionsstätte ausgewählt sein"), TEXT("A conveyor belt and conveyor lift must be selected for the factory")},
		{TEXT("Stromberechnung fehlgeschlagen"), TEXT("Power calculation failed")},
		{TEXT("Berechnung fehlgeschlagen"), TEXT("Calculation failed")},
		{TEXT("einschließlich Eigenverbrauch berechnet"), TEXT("including self-consumption calculated")},
		{TEXT("Für die Berechnung fehlt mindestens ein gültiges Endprodukt"), TEXT("At least one valid final product is required for calculation")},
		{TEXT("Rezept für"), TEXT("Recipe for")},
		{TEXT("gesetzt — jetzt Produktionsplan berechnen"), TEXT("selected — now calculate the production plan")},
		{TEXT("Automatische Rezeptwahl aktiviert"), TEXT("Automatic recipe selection enabled")},
		{TEXT("Zuerst einen Produktionsplan berechnen, damit alle externen Eingänge ermittelt werden"), TEXT("Calculate a production plan first so all external inputs can be determined")},
		{TEXT("Ungültige Eingangsmenge für"), TEXT("Invalid input rate for")},
		{TEXT("Mit diesen Eingängen ist keine positive Endproduktmenge möglich"), TEXT("These inputs cannot produce a positive final-product rate")},
		{TEXT("Alle Endprodukte proportional aus den Rohstofflimits skaliert — Engpass:"), TEXT("All final products scaled proportionally from resource limits — bottleneck:")},
		{TEXT("Stromziel aus Rohstofflimits skaliert — Engpass:"), TEXT("Power target scaled from resource limits — bottleneck:")},
		{TEXT("Zuerst einen Produktionsplan berechnen"), TEXT("Calculate a production plan first")},
		{TEXT("Speichern fehlgeschlagen"), TEXT("Save failed")},
		{TEXT("gespeichert"), TEXT("saved")},
		{TEXT("Bitte zuerst einen gespeicherten Plan aus der Liste auswählen"), TEXT("Select a saved plan from the list first")},
		{TEXT("Multiplayer-Plan-Liste konnte nicht geladen werden:"), TEXT("Multiplayer-plan list could not be loaded:")},
		{TEXT("Multiplayer-Plan laden fehlgeschlagen:"), TEXT("Loading multiplayer plan failed:")},
		{TEXT("Multiplayer-Plan speichern fehlgeschlagen:"), TEXT("Saving multiplayer plan failed:")},
		{TEXT("Multiplayer-Plan löschen fehlgeschlagen:"), TEXT("Deleting multiplayer plan failed:")},
		{TEXT("Empfangener Multiplayer-Plan ist ungültig:"), TEXT("Received multiplayer plan is invalid:")},
		{TEXT("Multiplayer-Plan-Aktualisierung fehlgeschlagen:"), TEXT("Multiplayer-plan update failed:")},
		{TEXT("Baufortschritt mit Multiplayer-Plan „"), TEXT("Build progress for multiplayer plan “")},
		{TEXT("lokal geändert; mit SPEICHERN als Multiplayer-Plan veröffentlichen"), TEXT("changed locally; use SAVE to publish as a multiplayer plan")},
		{TEXT("erstellt von"), TEXT("created by")},
		{TEXT("zuletzt"), TEXT("last")},
		{TEXT("wird geladen"), TEXT("is loading")},
		{TEXT("wird gespeichert"), TEXT("is being saved")},
		{TEXT("wird gelöscht"), TEXT("is being deleted")},
		{TEXT("synchronisiert"), TEXT("synchronized")},
		{TEXT("wurde inzwischen geändert"), TEXT("was changed in the meantime")},
		{TEXT("bitte neu laden und erneut versuchen"), TEXT("reload it and try again")},
		{TEXT("Nur der Ersteller"), TEXT("Only the creator")},
		{TEXT("darf diesen Multiplayer-Plan löschen"), TEXT("may delete this multiplayer plan")},
		{TEXT("lokale Änderungen bleiben erhalten"), TEXT("local changes are preserved")},
		{TEXT("neu laden oder unter neuem Namen speichern"), TEXT("reload or save under a new name")},
		{TEXT("Multiplayer-Pläne"), TEXT("Multiplayer plans")},
		{TEXT("Der Multiplayer-Plan"), TEXT("The multiplayer plan")},
		{TEXT("Multiplayer-Plan „"), TEXT("Multiplayer plan “")},
		{TEXT("Multiplayer-Plan"), TEXT("Multiplayer plan")},
		{TEXT("Ein Spieler"), TEXT("A player")},
		{TEXT("einem Spieler"), TEXT("another player")},
		{TEXT("geändert"), TEXT("changed")},
		{TEXT("wurde gelöscht"), TEXT("was deleted")},
		{TEXT("“ wird geladen"), TEXT("” is loading")},
		{TEXT("“ wird gespeichert"), TEXT("” is being saved")},
		{TEXT("“ wird gelöscht"), TEXT("” is being deleted")},
		{TEXT("“ synchronisiert"), TEXT("” synchronized")},
		{TEXT("“ wurde gelöscht"), TEXT("” was deleted")},
		{TEXT("Kein Multiplayer-Plan ausgewählt"), TEXT("No multiplayer plan selected")},
		{TEXT("Der Multiplayer-Plan überschreitet das Netzwerklimit von 512 KiB"), TEXT("The multiplayer plan exceeds the 512 KiB network limit")},
		{TEXT("Der gespeicherte Multiplayer-Plan überschreitet das Netzwerklimit von 512 KiB"), TEXT("The stored multiplayer plan exceeds the 512 KiB network limit")},
		{TEXT("Die Multiplayer-Verbindung für Multiplayer-Pläne ist noch nicht bereit"), TEXT("The multiplayer bridge for multiplayer plans is not ready yet")},
		{TEXT("Multiplayer-Pläne können nur vom lokalen Spieler angefragt werden"), TEXT("Multiplayer plans can only be requested by the local player")},
		{TEXT("Server-Autorität für die Planliste fehlt"), TEXT("Server authority for the plan catalog is missing")},
		{TEXT("Server-Autorität für den Planabruf fehlt"), TEXT("Server authority for the plan download is missing")},
		{TEXT("Server-Autorität zum Speichern fehlt"), TEXT("Server authority to save is missing")},
		{TEXT("Server-Autorität zum Löschen fehlt"), TEXT("Server authority to delete is missing")},
		{TEXT("Ungültige Multiplayer-Plan-Übertragung wurde abgewiesen"), TEXT("Invalid multiplayer-plan upload was rejected")},
		{TEXT("Ungültige Multiplayer-Plan-Blockanzahl wurde abgewiesen"), TEXT("Invalid multiplayer-plan chunk count was rejected")},
		{TEXT("Multiplayer-Plan-Datenblöcke sind unvollständig oder ungeordnet"), TEXT("Multiplayer-plan chunks are incomplete or out of order")},
		{TEXT("Multiplayer-Plan-Übertragung wurde nicht vollständig abgeschlossen"), TEXT("Multiplayer-plan upload did not complete")},
		{TEXT("Ungültiger Multiplayer-Plan-Download wurde abgewiesen"), TEXT("Invalid multiplayer-plan download was rejected")},
		{TEXT("Multiplayer-Plan-Download enthält unvollständige oder ungeordnete Datenblöcke"), TEXT("Multiplayer-plan download contains incomplete or out-of-order chunks")},
		{TEXT("Multiplayer-Plan-Download wurde nicht vollständig abgeschlossen"), TEXT("Multiplayer-plan download did not complete")},
		{TEXT("Planname und übertragene Daten stimmen nicht überein"), TEXT("Plan name and uploaded data do not match")},
		{TEXT("Die Spieleridentität für den Multiplayer-Plan fehlt"), TEXT("Player identity for the multiplayer plan is missing")},
		{TEXT("Der Multiplayer-Plan ist zu groß"), TEXT("The multiplayer plan is too large")},
		{TEXT("Der Multiplayer-Plan enthält einen ungültigen Zahlenwert"), TEXT("The multiplayer plan contains an invalid numeric value")},
		{TEXT("Der Multiplayer-Plan enthält ein ungültiges Ziel"), TEXT("The multiplayer plan contains an invalid target")},
		{TEXT("Der Multiplayer-Plan enthält einen ungültigen oder doppelten Knoten"), TEXT("The multiplayer plan contains an invalid or duplicate node")},
		{TEXT("Der Multiplayer-Plan enthält eine ungültige Verbindung"), TEXT("The multiplayer plan contains an invalid connection")},
		{TEXT("Der Multiplayer-Plan enthält ein ungültiges Rohstofflimit"), TEXT("The multiplayer plan contains an invalid resource limit")},
		{TEXT("Der Multiplayer-Plan enthält einen ungültigen Rezeptpfad"), TEXT("The multiplayer plan contains an invalid recipe path")},
		{TEXT("Der Multiplayer-Plan enthält zu viele Baukosteneinträge"), TEXT("The multiplayer plan contains too many construction-cost entries")},
		{TEXT("Der Multiplayer-Plan enthält ungültige Baukosten"), TEXT("The multiplayer plan contains invalid construction costs")},
		{TEXT("Der Multiplayer-Plan enthält einen zu langen Hinweistext"), TEXT("The multiplayer plan contains an excessively long note")},
		{TEXT("Vorhandener Multiplayer-Plan ist nicht lesbar:"), TEXT("Existing multiplayer plan cannot be read:")},
		{TEXT("Der Multiplayer-Plan existiert nicht mehr; bitte die Serverliste aktualisieren"), TEXT("The multiplayer plan no longer exists; refresh the server list")},
		{TEXT("Der Multiplayer-Plan wurde inzwischen geändert; bitte die Liste aktualisieren"), TEXT("The multiplayer plan was changed in the meantime; refresh the list")},
		{TEXT("Der Multiplayer-Plan wurde nicht gefunden"), TEXT("The multiplayer plan was not found")},
		{TEXT("Der Multiplayer-Plan konnte auf dem Server nicht gelöscht werden"), TEXT("The multiplayer plan could not be deleted from the server")},
		{TEXT("Ungültiger Dateiname für den Multiplayer-Plan"), TEXT("Invalid file name for the multiplayer plan")},
		{TEXT("beschädigte Multiplayer-Plan-Datei(en) wurden übersprungen"), TEXT("corrupted multiplayer-plan file(s) were skipped")},
		{TEXT("Laden fehlgeschlagen"), TEXT("Load failed")},
		{TEXT("Löschen fehlgeschlagen"), TEXT("Delete failed")},
		{TEXT("wurde gelöscht; der aktuelle Graph bleibt geöffnet"), TEXT("was deleted; the current graph remains open")},
		{TEXT("Gespeicherter Plan wiederhergestellt"), TEXT("Saved plan restored")},
		{TEXT("Gespeicherter Plan konnte nicht geladen werden"), TEXT("Saved plan could not be loaded")},
		{TEXT("Plan bei"), TEXT("Plan limited at")},
		{TEXT("Rechenschritten begrenzt"), TEXT("calculation steps")},
		{TEXT("Knoten begrenzt; Zielmenge oder Rezeptwahl verkleinern"), TEXT("nodes; reduce the target rate or change the recipe selection")},
		{TEXT("Direkt am Rohstoffknoten"), TEXT("Directly at the resource node")},
		{TEXT("Manuelle Rückführung/Zufuhr"), TEXT("Manual return/input")},
		{TEXT("RÜCKFÜHRUNG"), TEXT("RETURN FLOW")},
		{TEXT("Produktionskette unvollständig: Rechenlimit erreicht. Ziele verkleinern oder Rezeptwahl anpassen."), TEXT("Incomplete production chain: calculation limit reached. Reduce targets or adjust recipes.")},
		{TEXT("Materialbilanz nicht lösbar oder Rechenlimit erreicht. Plan nicht als versorgt verwenden."), TEXT("Material balance failed or calculation limit reached. Do not treat this plan as supplied.")},
		{TEXT("Materialbilanz: verbleibender ungedeckter Bedarf; Berechnung abgebrochen."), TEXT("Material balance: demand remains unmet; calculation aborted.")},
		{TEXT("Rückführung bilanziert. Zum Anfahren können Startmaterial, Puffer und geregelte Rücklaufzufuhr erforderlich sein."), TEXT("Return flow balanced. Startup may require initial material, buffers and controlled return flow.")},
		{TEXT("Rückführung deckt nicht den gesamten Bedarf: "), TEXT("Return flow does not cover all demand: ")},
		{TEXT("externe Zufuhr erforderlich."), TEXT("external supply required.")},
		{TEXT("Externe Zufuhr erforderlich:"), TEXT("External supply required:")},
		{TEXT("Rohstoffabbau:"), TEXT("Resource extraction:")},
		{TEXT("Kreislauf:"), TEXT("Cycle:")},
		{TEXT("Kreislauf bei "), TEXT("Cycle for ")},
		{TEXT(" wurde begrenzt"), TEXT(" was limited")},
		{TEXT("Gesperrtes Rezept:"), TEXT("Locked recipe:")},
		{TEXT("Zyklische Zufuhr:"), TEXT("Cyclic input:")},
		{TEXT("Externe Quelle:"), TEXT("External source:")},
		{TEXT("noch kein Rezept freigeschaltet"), TEXT("no recipe has been unlocked yet")},
		{TEXT(" ist noch kein Rezept freigeschaltet"), TEXT(" has no unlocked recipe yet")},
		{TEXT("blieb nur eine zyklische Rezeptkette"), TEXT("only a cyclic recipe chain remained")},
		{TEXT(" blieb nur eine zyklische Rezeptkette"), TEXT(" only has a cyclic recipe chain")},
		{TEXT("Die gewählte Rezeptvariante für"), TEXT("The selected recipe variant for")},
		{TEXT("ist in dieser Kette nicht verwendbar"), TEXT("cannot be used in this chain")},
		{TEXT("wurde genutzt"), TEXT("was used")},
		{TEXT("Rezepte möglich, automatisch"), TEXT("recipes available, automatically")},
		{TEXT("Maschinen gebaut"), TEXT("machines to build")},
		{TEXT("-Rohstoffknoten"), TEXT(" resource node")},
		{TEXT("Rohstoffknoten"), TEXT("resource node")},
		{TEXT("Abbauäquivalent"), TEXT("extraction equivalent")},
		{TEXT("Nebenprodukt-Lager:"), TEXT("Byproduct storage:")},
		{TEXT("Lagercontainer:"), TEXT("Storage container:")},
		{TEXT("Lagereingang Nebenprodukt:"), TEXT("Byproduct storage input:")},
		{TEXT("Lagereingang Generatorabfall:"), TEXT("Generator-waste storage input:")},
		{TEXT("Lagereingang Anlagenabfall:"), TEXT("Plant-waste storage input:")},
		{TEXT("Lagereingang:"), TEXT("Storage input:")},
		{TEXT("Nebenprodukt:"), TEXT("Byproduct:")},
		{TEXT("Generatorabfall:"), TEXT("Generator waste:")},
		{TEXT("Direktabbau:"), TEXT("Direct extraction:")},
		{TEXT("Abbau:"), TEXT("Extraction:")},
		{TEXT("Förderung:"), TEXT("Extraction:")},
		{TEXT("Wasserfläche"), TEXT("water surface")},
		{TEXT("Flüssigkeitsvorkommen"), TEXT("fluid deposit")},
		{TEXT("pro Extraktor"), TEXT("per extractor")},
		{TEXT("Ausgänge"), TEXT("outputs")},
		{TEXT("Eingänge"), TEXT("inputs")},
		{TEXT("Standard-Bohrkopf"), TEXT("Standard drill head")},
		{TEXT("Unrein"), TEXT("Impure")},
		{TEXT("Rein"), TEXT("Pure")},
		{TEXT("Freigeschaltete Rohrkapazität nicht geladen"), TEXT("Unlocked pipe capacity not loaded")},
		{TEXT("Keine passende freigeschaltete Rohrleitung gefunden"), TEXT("No suitable unlocked pipeline found")},
		{TEXT("Förderband- oder Liftkapazität nicht geladen"), TEXT("Conveyor belt or lift capacity not loaded")},
		{TEXT("Keine passende Förderband- und Förderlift-Kombination gefunden"), TEXT("No suitable conveyor belt and lift combination found")},
		{TEXT("parallele Leitungen"), TEXT("parallel pipes")},
		{TEXT("parallele Linien"), TEXT("parallel lines")},
		{TEXT("1 Leitung"), TEXT("1 pipe")},
		{TEXT("1 Linie"), TEXT("1 line")},
		{TEXT("Linien rein"), TEXT("lines in")},
		{TEXT("Linien raus"), TEXT("lines out")},
		{TEXT("Verbraucher"), TEXT("consumers")},
		{TEXT("Erzeuger"), TEXT("producers")},
		{TEXT("Infrastruktur"), TEXT("infrastructure")},
		{TEXT("Ø"), TEXT("avg.")},
		{TEXT("pro min"), TEXT("per min")},
		{TEXT("gesamt"), TEXT("total")},
		{TEXT("Fusionator"), TEXT("Merger")},
		{TEXT("Prioritätsfusion"), TEXT("Priority Merger")},
		{TEXT("Gewählte Transportstufe ist nicht verfügbar"), TEXT("Selected transport tier is unavailable")},
		{TEXT("wird verwendet"), TEXT("will be used")},
		{TEXT("Kein Endprodukt zur Produktionsstätte hinzugefügt"), TEXT("No final product has been added to the factory")},
		{TEXT("Eine Produktionsstätte kann höchstens 32 Endprodukte enthalten"), TEXT("A factory can contain at most 32 final products")},
		{TEXT("Mindestens ein Endprodukt ist ungültig"), TEXT("At least one final product is invalid")},
		{TEXT("Jede Endproduktmenge muss größer als 0 sein"), TEXT("Every final-product rate must be greater than 0")},
		{TEXT("Für die Endprodukte konnte kein gemeinsamer Produktionsplan erzeugt werden"), TEXT("No shared production plan could be generated for the final products")},
		{TEXT("Endprodukt:"), TEXT("Final product:")},
		{TEXT("Ziel:"), TEXT("Target:")},
		{TEXT("Reserve:"), TEXT("Reserve:")},
		{TEXT("Generatoren gebaut"), TEXT("generators to build")},
		{TEXT("Stromnetz:"), TEXT("Power grid:")},
		{TEXT("Stromautomatik:"), TEXT("Automatic power selection:")},
		{TEXT("Wetter-/standortabhängige Maximalleistung"), TEXT("Weather-/location-dependent maximum output")},
		{TEXT("Brennstofflose Stromerzeugung"), TEXT("Fuel-free power generation")},
		{TEXT("Direktkupplung"), TEXT("Direct coupling")},
		{TEXT("Direkt auf Heizkessel-Plattform"), TEXT("Directly on boiler platform")},
		{TEXT("Montagebasis"), TEXT("Mounting base")},
		{TEXT("Plattformen für Turbine und Generator"), TEXT("platforms for turbine and generator")},
		{TEXT("Plattformen für Heizkessel und Dampfkessel"), TEXT("platforms for heater and boiler")},
		{TEXT("Plattformen für Dampf-Kühlturm"), TEXT("platforms for steam cooling tower")},
		{TEXT("Plattformen für Rauchgas-Schornstein"), TEXT("platforms for flue-gas chimney")},
		{TEXT("Turbine und Generator auf Konverter-Plattform"), TEXT("Turbine and generator on converter platform")},
		{TEXT("Heizkessel und Dampfkessel auf Heizkessel-Plattform"), TEXT("Heater and boiler on boiler platform")},
		{TEXT("Dampf-Kühlturm auf Abgasplattform"), TEXT("Steam cooling tower on cooling platform")},
		{TEXT("Rauchgas-Schornstein auf Abgasplattform"), TEXT("Flue-gas chimney on cooling platform")},
		{TEXT("Kesseläquivalente"), TEXT("boiler equivalents")},
		{TEXT("Heizkesseläquivalente"), TEXT("heater equivalents")},
		{TEXT("Turbinenabgang"), TEXT("Turbine outlet")},
		{TEXT("Abgasbehandlung"), TEXT("Exhaust treatment")},
		{TEXT("Planung verwendet die wetter-/standortabhängige Maximalleistung von"), TEXT("Plan uses the weather-/location-dependent maximum output of")},
		{TEXT("je Generator"), TEXT("per generator")},
		{TEXT("ohne Brennstoff"), TEXT("without fuel")},
		{TEXT("Wasser/min"), TEXT("water/min")},
		{TEXT("Dampf/min"), TEXT("steam/min")},
		{TEXT("UPM je Satz"), TEXT("RPM per set")},
		{TEXT("Maximal"), TEXT("Maximum")},
		{TEXT("Sätze"), TEXT("sets")},
		{TEXT("Baukosten für"), TEXT("Construction costs for")},
		{TEXT("konnten nicht ermittelt werden"), TEXT("could not be determined")},
		{TEXT("nicht geladen"), TEXT("not loaded")},
		{TEXT("GESPERRT"), TEXT("LOCKED")},
		{TEXT("gesperrt"), TEXT("locked")},
		{TEXT("ZUFUHR + PRODUKTIONSSTUFE"), TEXT("INPUT + PRODUCTION STAGE")},
		{TEXT("PRODUKTIONSSTUFE"), TEXT("PRODUCTION STAGE")},
		{TEXT("Mittlere Länge"), TEXT("Average length")},
		{TEXT("je Graphverbindung"), TEXT("per graph connection")},
		{TEXT("Förderbandlinien"), TEXT("conveyor lines")},
		{TEXT("Rohrleitungen"), TEXT("pipelines")},
		{TEXT("nicht unterstützt"), TEXT("unsupported")},
		{TEXT("enthält keine"), TEXT("contains no")},
		{TEXT("leer oder beschädigt"), TEXT("empty or corrupted")},
		{TEXT("nicht lesbar"), TEXT("unreadable")},
		{TEXT("ungültiges JSON"), TEXT("invalid JSON")},
		{TEXT("nicht unterstützte Version"), TEXT("unsupported version")},
		{TEXT("Produktionsplan"), TEXT("production plan")},
		{TEXT("Gespeicherter"), TEXT("Saved")},
		{TEXT("konnte nicht gespeichert werden"), TEXT("could not be saved")},
		{TEXT("konnte nicht als JSON serialisiert werden"), TEXT("could not be serialized as JSON")},
		{TEXT("Produktionsplan konnte nicht gespeichert werden:"), TEXT("Production plan could not be saved:")},
		{TEXT("Gespeicherter Produktionsplan ist nicht lesbar:"), TEXT("Saved production plan is unreadable:")},
		{TEXT("Gespeicherter Produktionsplan konnte nicht gelöscht werden:"), TEXT("Saved production plan could not be deleted:")},
		{TEXT("Benannter Produktionsplan konnte nicht gelöscht werden:"), TEXT("Named production plan could not be deleted:")},
		{TEXT("Der Planname darf höchstens"), TEXT("The plan name may contain at most")},
		{TEXT("Zeichen lang sein"), TEXT("characters")},
		{TEXT("beschädigte Plan-Datei(en) wurden übersprungen"), TEXT("corrupted plan file(s) were skipped")},
		{TEXT("Plan „%s“ gespeichert"), TEXT("Plan “%s” saved")},
		{TEXT("Plan „%s“ geladen"), TEXT("Plan “%s” loaded")},
		{TEXT("Knoten „%s“ erledigt"), TEXT("Node “%s” completed")},
		{TEXT("Knoten „%s“ wieder geöffnet"), TEXT("Node “%s” reopened")},
		{TEXT("Produktionsplan gespeichert:"), TEXT("Production plan saved:")},
		{TEXT("Plan „"), TEXT("Plan “")},
		{TEXT("Knoten „"), TEXT("Node “")},
		{TEXT(" auf „"), TEXT(" set to “")},
		{TEXT("“ gespeichert"), TEXT("” saved")},
		{TEXT("“ geladen"), TEXT("” loaded")},
		{TEXT("“ erledigt"), TEXT("” completed")},
		{TEXT("“ wieder geöffnet"), TEXT("” reopened")},
		{TEXT("“ gesetzt"), TEXT("”")},
		// Generic fragments are deliberately last so they cannot break a longer phrase.
		{TEXT("Für "), TEXT("")},
		{TEXT(" mit "), TEXT(" with ")},
		{TEXT(" gewählt"), TEXT(" selected")},
		{TEXT("Stromversorgung"), TEXT("Power supply")},
		{TEXT("Stromplan"), TEXT("power plan")},
		{TEXT("Endprodukt(e)"), TEXT("final product(s)")},
		{TEXT("Endprodukte"), TEXT("final products")},
		{TEXT("Endprodukt"), TEXT("final product")},
		{TEXT("Knoten"), TEXT("nodes")},
		{TEXT("Verbindungen"), TEXT("connections")},
		{TEXT("Stromgeneratoren"), TEXT("power generators")},
		{TEXT("Transportstufen"), TEXT("transport tiers")},
		{TEXT("Produkte"), TEXT("products")},
		{TEXT("Rezepte"), TEXT("recipes")},
		{TEXT("Maschinen"), TEXT("machines")},
		{TEXT("Warnungen"), TEXT("warnings")},
		{TEXT("Bedarf"), TEXT("Demand")},
		{TEXT("benötigt"), TEXT("required")},
		{TEXT("verfügbar"), TEXT("available")},
		{TEXT("Förderband"), TEXT("Conveyor Belt")},
		{TEXT("Förderlift"), TEXT("Conveyor Lift")},
		{TEXT("Stufe"), TEXT("stage")},
		{TEXT("geladen"), TEXT("loaded")},
		{TEXT(" und "), TEXT(" and ")}
	};
}

bool SFPLocalization::IsGerman()
{
	const FString Language = FInternationalization::Get()
		.GetCurrentLanguage()->GetTwoLetterISOLanguageName();
	return Language.Equals(TEXT("de"), ESearchCase::IgnoreCase);
}

FString SFPLocalization::Select(const TCHAR* German, const TCHAR* English)
{
	return IsGerman() ? FString(German) : FString(English);
}

FString SFPLocalization::Translate(const FString& Source)
{
	if (Source.IsEmpty() || IsGerman())
	{
		return Source;
	}
	// Slate text attributes may be evaluated every frame. Cache completed
	// English strings so long summaries are not scanned repeatedly.
	static TMap<FString, FString> EnglishCache;
	if (const FString* Cached = EnglishCache.Find(Source))
	{
		return *Cached;
	}

	for (const FTranslationPair& Pair : ExactTranslations)
	{
		if (Source.Equals(Pair.German, ESearchCase::CaseSensitive))
		{
			const FString Result(Pair.English);
			EnglishCache.Add(Source, Result);
			return Result;
		}
	}

	// Longest source phrase wins. This keeps generic fallbacks such as
	// "Knoten" or "geladen" from damaging a complete sentence translation.
	static const TArray<int32> OrderedFragmentIndices = []()
	{
		TArray<int32> Indices;
		Indices.Reserve(UE_ARRAY_COUNT(FragmentTranslations));
		for (int32 Index = 0; Index < UE_ARRAY_COUNT(FragmentTranslations); ++Index)
		{
			Indices.Add(Index);
		}
		Indices.Sort([](const int32 Left, const int32 Right)
		{
			return FCString::Strlen(FragmentTranslations[Left].German)
				> FCString::Strlen(FragmentTranslations[Right].German);
		});
		return Indices;
	}();

	FString Result = Source;
	for (const int32 Index : OrderedFragmentIndices)
	{
		const FTranslationPair& Pair = FragmentTranslations[Index];
		Result.ReplaceInline(Pair.German, Pair.English, ESearchCase::CaseSensitive);
	}
	if (EnglishCache.Num() >= 1024)
	{
		EnglishCache.Reset();
	}
	EnglishCache.Add(Source, Result);
	return Result;
}

FText SFPLocalization::Text(const FString& Source)
{
	return FText::FromString(Translate(Source));
}

FText SFPLocalization::Text(const TCHAR* Source)
{
	return Text(Source != nullptr ? FString(Source) : FString());
}
